apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dinosaurs
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dinosaurs
    spec:
      containers:
      - name: dinosaurs-app
        image: johnchase/dinosaurs
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://dinosaurs-mysql.default.svc.cluster.local:3306/dinosaurs?useUnicode=true&characterEncoding=utf8&useSSL=false
        - name: JAVA_OPTS
          value: " -Xmx256m -Xms256m"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /management/health
            port: web
        livenessProbe:
          httpGet:
            path: /management/health
            port: web
          initialDelaySeconds: 180

