apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dinosaurs-mysql
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dinosaurs-mysql
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: mysql
        image: mysql:5.7.20
        args:
        - --lower-case-table-names=1
        - --skip-ssl
        - --character-set-server=utf8
        - --explicit-defaults-for-timestamp
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: 'yes'
        - name: MYSQL_DATABASE
          value: dinosaurs
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: dinosaurs-mysql
  namespace: default
spec:
  selector:
    app: dinosaurs-mysql
  ports:
  - port: 3306
