version: '2'
services:
    dinosaurs-app:
        image: dinosaurs
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dinosaurs-mysql:3306/dinosaurs?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dinosaurs-mysql:
        extends:
            file: mysql.yml
            service: dinosaurs-mysql
