version: '2'
services:
  dinosaurs:
    image: johnchase/dinosaurs
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://dinosaurs-mysql:3306/dinosaurs?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
      - JHIPSTER_SLEEP=30
      - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
      - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
      - JHIPSTER_METRICS_LOGS_ENABLED=true
      - JHIPSTER_METRICS_LOGS_REPORT_FREQUENCY=60
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=false
    ports:
      - '8080:8080'
  dinosaurs-mysql:
    image: 'mysql:8.0.20'
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dinosaurs
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp

  jhipster-elasticsearch:
    extends:
      file: jhipster-console.yml
      service: jhipster-elasticsearch
  jhipster-logstash:
    extends:
      file: jhipster-console.yml
      service: jhipster-logstash
    depends_on:
      - jhipster-elasticsearch
  jhipster-console:
    extends:
      file: jhipster-console.yml
      service: jhipster-console
    depends_on:
      - jhipster-elasticsearch
  jhipster-import-dashboards:
    extends:
      file: jhipster-console.yml
      service: jhipster-import-dashboards
    depends_on:
      - jhipster-elasticsearch
  jhipster-curator:
    extends:
      file: jhipster-console.yml
      service: jhipster-curator
    depends_on:
      - jhipster-elasticsearch
