apiVersion: v1
kind: Service
metadata:
  name: dinosaurs
  namespace: default
  labels:
    app: dinosaurs
spec:
  selector:
    app: dinosaurs
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
